# Generated by Django 2.1 on 2018-08-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(default='2018-08-20')),
                ('state', models.BooleanField(choices=[(True, 'Completed'), (False, 'Pending')], default=False)),
                ('alert_due_time', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
    ]
