# Generated by Django 2.1 on 2018-08-21 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_auto_20180821_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['-due_date']},
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='content',
            new_name='description',
        ),
    ]
