# Generated by Django 2.1 on 2018-08-21 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_auto_20180822_0105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['due_date']},
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
