# Generated by Django 2.1 on 2018-08-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0007_auto_20180822_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='alert_date',
            field=models.DateField(default='2018-08-21'),
        ),
        migrations.AddField(
            model_name='todolist',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
