# Generated by Django 2.1 on 2018-08-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0008_auto_20180822_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='state',
        ),
        migrations.AddField(
            model_name='todolist',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
